export const skills: SkillRecord[] = [
	{
		id: "1",
		title: "Write Code",
		slug: "write-code",
		description: "Ability to write clean, efficient, and maintainable code.",
		category: "Development",
		tags: ["programming", "typescript", "javascript"],
		installCommand: "npm install write-code",
		createdAt: "2026-04-23T10:50:00",
		authorClerkId: "auth123",
		authorEmail: "dev@example.com",
	},
	{
		id: "2",
		title: "Debug Applications",
		slug: "debug-applications",
		description:
			"Skill in identifying and fixing bugs in software applications.",
		category: "Development",
		tags: ["debugging", "tools", "errors"],
		installCommand: "npm install debug-applications",
		createdAt: "2026-04-23T10:50:00",
		authorClerkId: "auth456",
		authorEmail: "tester@example.com",
	},
	{
		id: "3",
		title: "Design Database Schema",
		slug: "design-database-schema",
		description:
			"Knowledge of designing normalized and efficient database schemas.",
		category: "Database",
		tags: ["sql", "schema", "design"],
		installCommand: "npm install design-database-schema",
		createdAt: "2026-04-23T10:50:00",
		authorClerkId: "auth789",
		authorEmail: "dbadmin@example.com",
	},
	{
		id: "4",
		title: "Build REST API",
		slug: "build-rest-api",
		description:
			"Ability to design and implement RESTful APIs for applications.",
		category: "Backend",
		tags: ["api", "rest", "express"],
		installCommand: "npm install build-rest-api",
		createdAt: "2026-04-23T10:50:00",
		authorClerkId: "auth321",
		authorEmail: "backend@example.com",
	},
	{
		id: "5",
		title: "Create Responsive UI",
		slug: "create-responsive-ui",
		description:
			"Skill in building user interfaces that adapt to different screen sizes.",
		category: "Frontend",
		tags: ["ui", "responsive", "css"],
		installCommand: "npm install create-responsive-ui",
		createdAt: "2026-04-23T10:50:00",
		authorClerkId: "auth654",
		authorEmail: "designer@example.com",
	},
];
